name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC login
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: eb91b50a-6694-4bf1-8f49-55da3e46ee7b
          tenant-id: 1eb73f30-ae95-483b-990a-3388241a7762
          subscription-id: 610a3b56-4971-4c4c-888c-177312c951b3
          auth-type: IDENTITY

      - name: Build and push image to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.WEBAPP_NAME }}:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.WEBAPP_NAME }}:latest

      - name: Deploy to Azure Web App (Linux)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          images: ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.WEBAPP_NAME }}:latest
