name: Build and Push to ACR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
  push:
    branches:
      - main

env:
  ACR_NAME: myregistry123
  IMAGE_NAME: myapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG ./my-app
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
