name: Deploy to Azure Web App from ACR

on:
  workflow_dispatch:  # Manually triggered
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: MyResourceGroup
  WEBAPP_NAME: mywebappdocker123
  ACR_NAME: myregistry123 # without .azurecr.io
  IMAGE_NAME: myapp:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure ACR Login
      run: az acr login --name $ACR_NAME

    - name: Deploy to Web App
      run: |
        az webapp config container set \
          --name $WEBAPP_NAME \
          --resource-group $RESOURCE_GROUP \
          --docker-custom-image-name $ACR_NAME.azurecr.io/$IMAGE_NAME \
          --docker-registry-server-url https://$ACR_NAME.azurecr.io

    - name: Restart Web App
      run: |
        az webapp restart --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP
