name: Build and Deploy to Azure Web App from ACR

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: MyResourceGroup
  WEBAPP_NAME: mywebappdocker123
  ACR_NAME: myregistry123 # without .azurecr.io
  IMAGE_NAME: myapp
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure ACR Login
      run: az acr login --name $ACR_NAME

    - name: Build and Push Docker image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME ./my-app
        az acr login --name $ACR_NAME
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME


    - name: Deploy to Web App from ACR
      run: |
        az webapp config container set \
          --name $WEBAPP_NAME \
          --resource-group $RESOURCE_GROUP \
          --docker-custom-image-name $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG \
          --docker-registry-server-url https://$ACR_NAME.azurecr.io

    - name: Restart Web App
      run: |
        az webapp restart --name $WEBAPP_NAME --resource-group $RESOURCE_GROUP
