name: Deploy to Azure Web App from ACR

on:
  workflow_run:
    workflows: ["Build and Push to ACR"]
    types:
      - completed

env:
  RESOURCE_GROUP: MyResourceGroup
  WEBAPP_NAME: mywebappdocker123
  ACR_NAME: myregistry123
  IMAGE_NAME: myapp

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download Artifact from Build Workflow
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          path: .

      - name: Read Image Tag
        id: read_tag
        run: echo "IMAGE_TAG=$(cat image_tag.txt)" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Web App from ACR
        run: |
          echo "Deploying image: $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG"
          az webapp config container set \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG \
            --docker-registry-server-url https://$ACR_NAME.azurecr.io

      - name: Restart Web App
        run: |
          echo "Restarting Web App: $WEBAPP_NAME"
          az webapp restart \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP
